### PR TITLE
Update README.md en CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Sander3003**
Added new URL's

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://52.16.237.165:80/OSGP/Platform?pullRequest=463) <br/>You should sign our Contributor License Agreement in order to get your pull request merged.<br/>

**Comment by Sander3003** [comment]
@bvdzwet can you double check if the missing headers are fixed? I see that changes in the dev branch are pushed to the master branch in the last 8 months.

**Comment by bvdzwet** [comment]
@Sander3003 I opened a number of files and checked if they contained a license header, which they did.

I don't know of a good automated way to check for proper license headers in all files.
Some license plugins for Maven exist (license-maven-plugin from com.mycila and org.codehaus.mojo), but I didn't see quickly how to configure them to work (the license header is not entirely static, files contain the copyright year of the year they were initially created, which varies).

**Comment by Sander3003** [comment]
@pczeeuw will look into a permanent fix for header checking (OC-36). If you agree with my chances you can merge them or give an oke so I can merge them.

**Comment by bvdzwet** [comment]
@Sander3003 I agree with the changes, but the CLAAdmin is not happy yet. You need to sign the CLA for each separate OSGP repository you contribute to, not only once for everything OSGP.

**Pull request merged**
